security:
    encoders:
      \Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
      ROLE_ADMIN: ROLE_USER
      ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        in_memory:
            memory:
              users:
                superadmin:
                  password: superadmin
                  roles:
                    - ROLE_SUPER_ADMIN
                admin:
                  password: admin
                  roles:
                    - ROLE_ADMIN
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login_firewall:
            pattern: ^/login$
            anonymous: ~

        secured:
          pattern: ^/
          anonymous: ~
          form_login:
            csrf_provider: form.csrf_provider
            login_path: login
            check_path: login_check
            default_target_path: admin_house
#            always_use_default_target_path: true
          logout: ~

#        default:
#            anonymous: ~

    access_control:
      - { path: ^/(_(profiler|wdt)|css|img|js), role: [IS_AUTHENTICATED_ANONYMOUSLY] } # Dev tools, assets
      - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/admin/, roles: ROLE_ADMIN }
      - { path: ^/, roles: ROLE_ADMIN }
