security:
    role_hierarchy:
      ROLE_ADMIN: ROLE_USER
      ROLE_SUPER_ADMIN: ROLE_ADMIN
    providers:
        in_memory:
            memory:
              users:
                superadmin:
                  password: superadmin
                  roles:
                    - ROLE_SUPER_ADMIN
                admin:
                  password: admin
                  roles:
                    - ROLE_ADMIN
    encoders:
      \Symfony\Component\Security\Core\User\User: plaintext

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        secured:
          pattern: ^/
          anonymous: ~
          form_login:
            csrf_provider: form.csrf_provider
            login_path: login
            check_path: login_check
            always_use_default_target_path: true
          logout: ~

        default:
            anonymous: ~

    access_control:
      - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/admin/, roles: ROLE_ADMIN }
