<?php

namespace Globalcom\DoormanBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EntranceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntranceRepository extends EntityRepository
{
}
