<?php

namespace Globalcom\DoormanBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr\Join;

/**
 * KeyGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KeyGroupRepository extends EntityRepository
{
    public function getQbAllInEntrance(Entrance $entrance)
    {
        $qb = $this->createQueryBuilder('kg');
        $qb
            ->innerJoin('Globalcom\DoormanBundle\Entity\KeyGroupHasEntrance', 'kghe', Join::WITH, 'kghe.keyGroup = kg')
            ->innerJoin('Globalcom\DoormanBundle\Entity\Entrance', 'e', Join::WITH, 'kghe.entrance = e')
            ->where('e = :entrance')
            ->setParameter('entrance', $entrance)
        ;

        return $qb;
    }

    public function getQbAllNotInEntrance(Entrance $entrance)
    {
        $qb = $this->createQueryBuilder('kg');

        if ($entrance->getKeyGroups()->count()) {
            $entranceKeygroupsIds = $entrance
                ->getKeyGroups()
                ->map(
                    function (KeyGroup $keyGroup)
                    {
                        return $keyGroup->getId();
                    })
                ->toArray()
            ;

            $qb->where($qb->expr()->notIn('kg.id', $entranceKeygroupsIds));
        }

        return $qb;
    }

    public function findAllNotInEntrance(Entrance $entrance)
    {
        return $this->getQbAllNotInEntrance($entrance)->getQuery()->getResult();
    }
}
