<?php

namespace Globalcom\DoormanBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * KeyGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KeyGroupRepository extends EntityRepository
{
}
