<?php

namespace Globalcom\DoormanBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr\Join;

/**
 * KeyGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KeyGroupRepository extends EntityRepository
{
    public function getQbAllInEntrance(Entrance $entrance)
    {
        $qb = $this->createQueryBuilder('kg');
        $qb
            ->innerJoin('kg.entrances', 'e', Join::WITH, 'e = :entrance')
            ->setParameter('entrance', $entrance);

        return $qb;
    }

    public function getQbAllNotInEntrance(Entrance $entrance)
    {
        $qb = $this->createQueryBuilder('kg');
        $qb
            ->innerJoin('kg.entrances', 'e', Join::WITH, 'e != :entrance')
            ->setParameter('entrance', $entrance);

        return $qb;
    }

    public function findAllNotInEntrance(Entrance $entrance)
    {

    }
}
