<?php

namespace Globalcom\DoormanBundle\DBALType;

use Doctrine\DBAL\Types\DateTimeType;
use Doctrine\DBAL\Platforms\AbstractPlatform;

class DateTimeU extends DateTimeType
{
    public function getName()
    {
        return parent::getName(); // TODO: Change the autogenerated stub
    }

    public function convertToDatabaseValue($value, AbstractPlatform $platform)
    {
        return parent::convertToDatabaseValue($value, $platform); // TODO: Change the autogenerated stub
    }

    public function convertToPHPValue($value, AbstractPlatform $platform)
    {
        return parent::convertToPHPValue($value, $platform); // TODO: Change the autogenerated stub
    }

} 
